language: node_js
os: linux
dist: xenial
node_js: [14]

install:
  - |
    sudo apt-get update
    sudo apt-get install -y \
       curl \
       xvfb \
       libglib2.0-0 \
       libnss3 \
       libatk1.0-0 \
       libatk-bridge2.0-0 \
       libgtk-3-0 \
       libasound2

  - nvm install v16.15.0

  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

  - yarn

script:
  - yarn compile
  - yarn pretest
  # Setting these two variables get rid of warnings from vscode about
  # being unable to connect to the bus
  - export DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'
  - export DBUS_SESSION_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'
  - yarn test:extension

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - yarn run semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
