enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@apidevtools/swagger-parser@*":
    peerDependenciesMeta:
      openapi-types:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
