import assert from 'assert';
import * as path from 'path';
import * as vscode from 'vscode';
import { GenerateOpenApi } from '../../../src/commands/generateOpenApi';
import { retry } from '../../../src/util';
import { waitForExtension } from '../util';

describe('OpenAPI generation', () => {
  beforeEach(waitForExtension);

  it('opens a new window containing an OpenAPI definition file', async () => {
    vscode.commands.executeCommand(GenerateOpenApi, vscode.ViewColumn.Active);
    await retry(
      () => {
        const { activeTextEditor } = vscode.window;
        const isYaml = activeTextEditor?.document.languageId === 'yaml';
        const firstLine = activeTextEditor?.document.getText(new vscode.Range(0, 0, 1, 0)).trim();
        const isOpenApi = firstLine === '# Generated by: @appland/appmap openapi';
        if (!isYaml || !isOpenApi) {
          throw new Error(`waiting for generated OpenAPI definitions`);
        }
      },
      20,
      500
    );
  });
});
