name: Add new issues to project tracker

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/getappmap/projects/15
          github-token: ${{ secrets.ADD_TO_PROJECT_BOARD_PAT }}
