name: Release

on:
  push:
    branches: [master]

jobs:
  validation:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    name: Validate
    uses: ./.github/workflows/test.yml

  release:
    name: Package and release to VS Code marketplace
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: npm i -g yarn
      - run: yarn install --immutable
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_VSCE_TOKEN }}
